GET http://localhost:7090/products

###
GET http://localhost:7090/products


###
POST http://localhost:7090/products
Content-type: application/json

{ 
"name": "",
"description": "",
"price":"",
"img": ""
}

###
DELETE http://localhost:7090/products

###
PATCH http://localhost:7090
Content-type: application/json

{
    "name": "Brush"
}