GET http://localhost:7090/users

###
GET http://localhost:7090/users


###
POST http://localhost:7090/users
Content-type: application/json

{ 
"user_fullname": "Yasseen Davids",
"email": "yaseendavids@gmail.com@gmail.com",
"password":"yaaseen0000",
"phone_number": "0815253666"
}

###
DELETE http://localhost:7090/users/621cd167413a1daa40586545

###
PATCH http://localhost:7090
Content-type: application/json

{
    "user_fullname": "Craig Braaf"
}