GET http://localhost:7003/products

###
GET http://localhost:7003/products


###
POST http://localhost:7003/products
Content-type: application/json

{ 
"title": "Steam Hair Straightener Flat Iron",
"price": "R479.00",
"category":"Flat-Iron",
"description": "Steam Technology: designed with new steam feature, 5 conditioning steam vents on the heating plate",
"img":"https://i.postimg.cc/hjYVYvQs/flat-iron.jpg"  
}

###
DELETE http://localhost:7003/users/621cd0d4413a1daa40586543

###
PATCH http://localhost:7003
Content-type: application/json

{
    "user_fullname": "Craig Braaf"
}